  # Just like the config/database.yml this file requires an entry for each environment
  # http://aws.amazon.com/security-credentials
development:
    access_key_id: ENV['AWS_ACCESS_KEY']
    secret_access_key: ENV['AWS_SECRET_KEY']

test:
    access_key_id: ENV['AWS_ACCESS_KEY']
    secret_access_key: ENV['AWS_SECRET_KEY']

production:
    access_key_id: ENV['AWS_ACCESS_KEY']
    secret_access_key: ENV['AWS_SECRET_KEY']