development:
  api_key:   ENV['LAST_FM_KEY']
  secret:   ENV['LAST_FM_SECRET']

test:
  api_key:   ENV['LAST_FM_KEY']
  secret:   ENV['LAST_FM_SECRET']
  
production:
  api_key:   ENV['LAST_FM_KEY']
  secret:   ENV['LAST_FM_SECRET']
  